
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 29
#define YY_END_OF_BUFFER 30
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[387] =
    {   0,
        0,    0,   30,   28,   27,   27,   11,   10,   21,   19,
       12,   20,    6,   22,   28,    2,    9,    7,   16,   18,
       17,    5,   26,   27,    0,    2,    0,    0,    0,    2,
        2,   23,    8,   14,   15,   13,    5,    5,    5,   26,
       25,    3,   24,   24,    0,    0,    2,    0,    2,    2,
       23,    5,    5,   24,   24,    0,    0,    0,    2,    0,
        0,    2,    2,    5,    5,    0,    0,    0,    0,    2,
        0,    0,    2,    2,    5,    5,    0,    0,    0,    0,
        0,    0,    0,    2,    0,    0,    2,    2,    5,    5,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    0,

        0,    2,    2,    5,    5,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    2,    0,    0,    2,
        2,    5,    5,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    2,    0,    0,    2,    2,
        5,    5,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    2,    0,    0,
        2,    2,    5,    5,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        2,    0,    0,    2,    1,    5,    5,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    1,    1,    1,    0,    1,
        1,    5,    5,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    1,    1,
        0,    1,    1,    1,    1,    1,    1,    5,    5,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    1,    1,    0,    1,    1,    1,    1,
        1,    1,    5,    5,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    1,    1,    0,    1,    1,
        1,    1,    1,    5,    5,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    1,    1,    0,    1,    1,

        1,    1,    1,    5,    5,    0,    0,    0,    0,    0,
        0,    0,    1,    1,    0,    1,    1,    1,    1,    1,
        5,    5,    0,    0,    0,    0,    0,    0,    1,    1,
        0,    1,    1,    1,    1,    1,    5,    5,    0,    0,
        0,    1,    1,    0,    1,    1,    1,    1,    1,    5,
        5,    0,    0,    1,    1,    0,    1,    1,    1,    1,
        1,    5,    4,    1,    0,    1,    1,    1,    1,    1,
        4,    4,    0,    1,    1,    1,    1,    1,    4,    4,
        1,    1,    1,    1,    1,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    4,
        5,    6,    7,    8,    9,   10,   11,   12,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,   16,
       17,   18,    1,    1,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
        1,    1,    1,    1,   20,    1,   19,   19,   19,   19,

       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   21,    1,   22,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[23] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    4,    4,    1,    1,    1,    1,    1,    4,    5,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[391] =
    {   0,
        0,    0,  526,  976,   21,   23,  976,  976,  976,  976,
      976,   15,  976,  976,   19,   30,  502,  976,   16,  976,
      495,   38,  483,   33,    0,    0,   33,  488,  479,   28,
       50,  481,  976,  976,  976,  976,    0,   58,    0,  463,
      976,   42,   53,   55,  474,   67,   62,  464,    0,   73,
      460,    0,   81,   76,   78,  450,   90,   95,   92,   97,
      443,    0,  103,    0,  111,  105,  436,  116,  123,  107,
      125,  429,    0,  130,    0,  138,  423,  132,  143,  150,
      422,  152,  157,  108,  159,  417,    0,  164,    0,  172,
      166,  416,  177,  184,  186,  415,  191,  193,  134,  198,

      405,    0,  203,    0,  211,  404,  205,  216,  223,  397,
      225,  230,  232,  390,  237,  239,  135,  244,  383,    0,
      249,    0,  257,  251,  376,  262,  269,  271,  369,  276,
      278,  283,  363,  285,  290,  168,  292,  362,    0,  297,
        0,  305,  357,  299,  310,  317,  356,  319,  324,  326,
      355,  331,  333,  338,  342,  340,  345,  169,  347,  335,
        0,  352,    0,  360,  354,  328,  365,  372,  374,  321,
      379,  381,  386,  314,  388,  393,  395,  308,  400,  402,
      207,  407,  307,    0,  412,    0,  420,  302,  414,  425,
      432,  301,  434,  439,  441,  300,  446,  448,  453,  287,

      455,  460,  462,  280,  467,  469,  208,  474,  273,    0,
      196,    0,  476,  481,  266,  488,  490,  495,  260,  497,
      502,  504,  254,  509,  511,  516,  252,  518,  523,  525,
      242,  530,  532,  253,  537,    0,    0,    0,  539,  241,
      544,  551,  553,  234,  558,  560,  565,  227,  567,  572,
      574,  220,  579,  581,  586,  206,  588,  593,  595,  600,
      602,    0,    0,  604,  609,  188,  616,  618,  623,  181,
      625,  630,  632,  167,  637,  639,  644,  154,  646,  651,
      653,  658,  660,    0,  662,  147,  667,  674,  676,  133,
      681,  683,  688,  120,  690,  695,  697,  106,  702,  704,

      709,  711,  716,    0,  718,  723,   85,  730,  732,  737,
       83,  739,  744,  746,   74,  751,  753,  758,  760,  765,
        0,  767,   71,  772,  779,  781,   60,  786,  788,  793,
       51,  795,  800,  802,  807,  809,    0,  811,  816,   43,
      823,  825,  830,   40,  832,  837,  839,  844,  846,    0,
      848,   35,  853,  860,  862,   31,  867,  869,  874,  876,
      881,    0,  883,  888,   24,  895,  897,  902,  904,  909,
        0,  911,   17,  916,  923,  925,  930,  932,    0,    0,
      937,  939,  944,  946,  951,  976,  964,  967,  969,  970
    } ;

static yyconst flex_int16_t yy_def[391] =
    {   0,
      386,    1,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  387,  386,   15,   16,  386,  388,  386,   16,
      386,  389,  386,  386,  386,  386,   22,  386,  390,  387,
      386,  386,  386,  386,  388,  386,   31,  386,   47,  386,
      389,   38,  386,  386,  386,  386,  386,  386,   50,  386,
      386,   59,  386,   53,  386,  386,  386,  386,  386,   63,
      386,  386,   70,  386,   65,  386,  386,  386,  386,  386,
      386,  386,  386,   74,  386,  386,   84,  386,   76,  386,
      386,  386,  386,  386,  386,  386,  386,  386,   88,  386,

      386,   99,  386,   90,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  103,  386,  386,  117,
      386,  105,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  121,  386,  386,  136,  386,
      123,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  140,  386,  386,
      158,  386,  142,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      162,  386,  386,  181,  386,  164,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,

      386,  386,  386,  386,  386,  386,  185,  386,  386,  207,
      185,  187,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  211,  386,  234,  211,  213,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  234,  239,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  264,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,

      386,  386,  386,  285,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      305,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  322,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  338,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  351,  386,  386,  386,  386,  386,  386,  386,  386,
      363,  386,  386,  386,  386,  386,  386,  386,  372,  372,
      386,  386,  386,  386,  386,    0,  386,  386,  386,  386
    } ;

static yyconst flex_int16_t yy_nxt[999] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,    4,
       23,    4,   24,   24,   24,   24,   25,   26,   27,  381,
       25,   25,   34,   35,   24,   24,  376,   28,   29,   27,
       47,   30,   31,  368,   42,   42,   28,  364,   32,   37,
       37,   43,  359,   42,   42,  355,   38,   39,   48,   27,
       43,   49,   50,  347,   54,   54,   55,   55,   32,   52,
       52,   54,  343,   55,   59,   56,   53,   39,   57,   58,
       28,   61,   27,  339,   62,   63,  334,   54,   54,   55,
       55,   32,   64,   64,   54,  330,   55,  326,   56,   65,

       39,   57,   58,   67,   70,   67,   68,   69,   68,   69,
       28,   72,   27,   77,   73,   74,   78,   79,  318,   84,
       99,   32,   75,   75,   67,   28,   28,   68,   69,   76,
       39,   81,  314,   81,   82,   83,   82,   83,   86,   27,
       77,   87,   88,   78,   79,  310,  117,  136,   32,   89,
       89,   92,   28,   28,   93,   94,   90,   39,   92,  306,
       81,   93,   94,   82,   83,   96,  301,   96,   97,   98,
       97,   98,  101,   27,  106,  102,  103,  107,  108,  297,
      158,  181,   32,  104,  104,   92,   28,   28,   93,   94,
      105,   39,  110,  293,  110,  111,  112,  111,  112,   96,

      289,  114,   97,   98,  115,  116,  114,  236,  237,  115,
      116,  119,   27,  106,  120,  121,  107,  108,  281,  207,
      234,   32,  122,  122,  125,   28,   28,  126,  127,  123,
       39,  125,  277,  110,  126,  127,  111,  112,  129,  273,
      129,  130,  131,  130,  131,  114,  269,  133,  115,  116,
      134,  135,  133,  265,  259,  134,  135,  138,   27,  143,
      139,  140,  144,  145,  255,  262,  251,   32,  141,  141,
      125,   28,  247,  126,  127,  142,   39,  147,  243,  147,
      148,  149,  148,  149,  129,  235,  151,  130,  131,  152,
      153,  151,  230,  133,  152,  153,  134,  135,  155,  226,

      155,  156,  157,  156,  157,  160,   27,  143,  161,  162,
      144,  145,  222,  218,  214,   32,  163,  163,  166,  208,
      203,  167,  168,  164,   39,  166,  199,  147,  167,  168,
      148,  149,  170,  195,  170,  171,  172,  171,  172,  151,
      191,  174,  152,  153,  175,  176,  174,  182,  155,  175,
      176,  156,  157,  178,  177,  178,  179,  180,  179,  180,
      183,   27,  188,  184,  185,  189,  190,  173,  169,  165,
       32,  186,  186,  166,  159,  154,  167,  168,  187,   39,
      192,  150,  192,  193,  194,  193,  194,  170,  146,  196,
      171,  172,  197,  198,  196,  137,  174,  197,  198,  175,

      176,  200,  132,  200,  201,  202,  201,  202,  178,  128,
      204,  179,  180,  205,  206,  204,  124,  118,  205,  206,
      209,   27,  188,  210,  211,  189,  190,  113,  109,  100,
       32,  212,  212,  215,   95,   91,  216,  217,  213,   39,
      215,   85,  192,  216,  217,  193,  194,  219,   80,  219,
      220,  221,  220,  221,  196,   71,  223,  197,  198,  224,
      225,  223,   66,  200,  224,  225,  201,  202,  227,   44,
      227,  228,  229,  228,  229,  204,   60,  231,  205,  206,
      232,  233,  231,   44,   41,  232,  233,  238,  238,  240,
       44,   46,  241,  242,  239,   39,  215,   44,  244,  216,

      217,  245,  246,  244,   41,  219,  245,  246,  220,  221,
      248,   36,  248,  249,  250,  249,  250,  223,   33,  252,
      224,  225,  253,  254,  252,  386,  227,  253,  254,  228,
      229,  256,  386,  256,  257,  258,  257,  258,  231,  386,
      231,  232,  233,  260,  261,  231,  386,  386,  260,  261,
      263,  263,  240,  386,  386,  241,  242,  264,   39,  266,
      386,  266,  267,  268,  267,  268,  244,  386,  270,  245,
      246,  271,  272,  270,  386,  248,  271,  272,  249,  250,
      274,  386,  274,  275,  276,  275,  276,  252,  386,  278,
      253,  254,  279,  280,  278,  386,  256,  279,  280,  257,

      258,  256,  386,  256,  282,  283,  282,  283,  231,  386,
      231,  260,  261,  260,  261,  284,  284,  286,  386,  386,
      287,  288,  285,   39,  266,  386,  290,  267,  268,  291,
      292,  290,  386,  270,  291,  292,  271,  272,  294,  386,
      294,  295,  296,  295,  296,  274,  386,  298,  275,  276,
      299,  300,  298,  386,  278,  299,  300,  279,  280,  278,
      386,  278,  302,  303,  302,  303,  256,  386,  256,  282,
      283,  282,  283,  304,  304,  286,  386,  386,  287,  288,
      305,   39,  307,  386,  307,  308,  309,  308,  309,  290,
      386,  311,  291,  292,  312,  313,  311,  386,  294,  312,

      313,  295,  296,  315,  386,  315,  316,  317,  316,  317,
      298,  386,  298,  299,  300,  319,  320,  298,  386,  278,
      319,  320,  302,  303,  278,  386,  386,  302,  303,  321,
      321,  323,  386,  386,  324,  325,  322,   39,  307,  386,
      327,  308,  309,  328,  329,  327,  386,  311,  328,  329,
      312,  313,  331,  386,  331,  332,  333,  332,  333,  315,
      386,  315,  316,  317,  335,  336,  315,  386,  298,  335,
      336,  319,  320,  298,  386,  386,  319,  320,  337,  337,
      323,  386,  386,  324,  325,  338,   39,  340,  386,  340,
      341,  342,  341,  342,  327,  386,  344,  328,  329,  345,

      346,  344,  386,  331,  345,  346,  332,  333,  331,  386,
      331,  348,  349,  348,  349,  315,  386,  315,  335,  336,
      335,  336,  350,  350,  352,  386,  386,  353,  354,  351,
       39,  340,  386,  356,  341,  342,  357,  358,  356,  386,
      344,  357,  358,  345,  346,  344,  386,  344,  360,  361,
      360,  361,  331,  386,  331,  348,  349,  348,  349,  362,
      362,  352,  386,  386,  353,  354,  363,   39,  365,  386,
      365,  366,  367,  366,  367,  356,  386,  356,  357,  358,
      369,  370,  356,  386,  344,  369,  370,  360,  361,  344,
      386,  386,  360,  361,  371,  371,  373,  386,  386,  374,

      375,  372,   39,  365,  386,  365,  366,  367,  377,  378,
      365,  386,  356,  377,  378,  369,  370,  356,  386,  386,
      369,  370,  379,  379,  373,  386,  386,  374,  375,  380,
       39,  373,  386,  373,  382,  383,  382,  383,  365,  386,
      365,  377,  378,  377,  378,  373,  386,  373,  384,  385,
      382,  383,  373,  386,  373,  382,  383,  384,  385,  373,
      386,  386,  384,  385,   40,  386,   40,   40,   40,   45,
       45,   51,   51,   39,   39,    3,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386

    } ;

static yyconst flex_int16_t yy_chk[999] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    5,    6,    6,   12,   12,   15,  373,
       15,   15,   19,   19,   24,   24,  365,   15,   16,   16,
       30,   16,   16,  356,   27,   27,   30,  352,   16,   22,
       22,   27,  344,   42,   42,  340,   22,   22,   31,   31,
       42,   31,   31,  331,   43,   43,   44,   44,   31,   38,
       38,   43,  327,   44,   47,   46,   38,   38,   46,   46,
       47,   50,   50,  323,   50,   50,  315,   54,   54,   55,
       55,   50,   53,   53,   54,  311,   55,  307,   57,   53,

       53,   57,   57,   58,   59,   60,   58,   58,   60,   60,
       59,   63,   63,   66,   63,   63,   66,   66,  298,   70,
       84,   63,   65,   65,   68,   70,   84,   68,   68,   65,
       65,   69,  294,   71,   69,   69,   71,   71,   74,   74,
       78,   74,   74,   78,   78,  290,   99,  117,   74,   76,
       76,   79,   99,  117,   79,   79,   76,   76,   80,  286,
       82,   80,   80,   82,   82,   83,  278,   85,   83,   83,
       85,   85,   88,   88,   91,   88,   88,   91,   91,  274,
      136,  158,   88,   90,   90,   93,  136,  158,   93,   93,
       90,   90,   94,  270,   95,   94,   94,   95,   95,   97,

      266,   98,   97,   97,   98,   98,  100,  211,  211,  100,
      100,  103,  103,  107,  103,  103,  107,  107,  256,  181,
      207,  103,  105,  105,  108,  181,  207,  108,  108,  105,
      105,  109,  252,  111,  109,  109,  111,  111,  112,  248,
      113,  112,  112,  113,  113,  115,  244,  116,  115,  115,
      116,  116,  118,  240,  231,  118,  118,  121,  121,  124,
      121,  121,  124,  124,  227,  234,  223,  121,  123,  123,
      126,  234,  219,  126,  126,  123,  123,  127,  215,  128,
      127,  127,  128,  128,  130,  209,  131,  130,  130,  131,
      131,  132,  204,  134,  132,  132,  134,  134,  135,  200,

      137,  135,  135,  137,  137,  140,  140,  144,  140,  140,
      144,  144,  196,  192,  188,  140,  142,  142,  145,  183,
      178,  145,  145,  142,  142,  146,  174,  148,  146,  146,
      148,  148,  149,  170,  150,  149,  149,  150,  150,  152,
      166,  153,  152,  152,  153,  153,  154,  160,  156,  154,
      154,  156,  156,  157,  155,  159,  157,  157,  159,  159,
      162,  162,  165,  162,  162,  165,  165,  151,  147,  143,
      162,  164,  164,  167,  138,  133,  167,  167,  164,  164,
      168,  129,  169,  168,  168,  169,  169,  171,  125,  172,
      171,  171,  172,  172,  173,  119,  175,  173,  173,  175,

      175,  176,  114,  177,  176,  176,  177,  177,  179,  110,
      180,  179,  179,  180,  180,  182,  106,  101,  182,  182,
      185,  185,  189,  185,  185,  189,  189,   96,   92,   86,
      185,  187,  187,  190,   81,   77,  190,  190,  187,  187,
      191,   72,  193,  191,  191,  193,  193,  194,   67,  195,
      194,  194,  195,  195,  197,   61,  198,  197,  197,  198,
      198,  199,   56,  201,  199,  199,  201,  201,  202,   51,
      203,  202,  202,  203,  203,  205,   48,  206,  205,  205,
      206,  206,  208,   45,   40,  208,  208,  213,  213,  214,
       32,   29,  214,  214,  213,  213,  216,   28,  217,  216,

      216,  217,  217,  218,   23,  220,  218,  218,  220,  220,
      221,   21,  222,  221,  221,  222,  222,  224,   17,  225,
      224,  224,  225,  225,  226,    3,  228,  226,  226,  228,
      228,  229,    0,  230,  229,  229,  230,  230,  232,    0,
      233,  232,  232,  233,  233,  235,    0,    0,  235,  235,
      239,  239,  241,    0,    0,  241,  241,  239,  239,  242,
        0,  243,  242,  242,  243,  243,  245,    0,  246,  245,
      245,  246,  246,  247,    0,  249,  247,  247,  249,  249,
      250,    0,  251,  250,  250,  251,  251,  253,    0,  254,
      253,  253,  254,  254,  255,    0,  257,  255,  255,  257,

      257,  258,    0,  259,  258,  258,  259,  259,  260,    0,
      261,  260,  260,  261,  261,  264,  264,  265,    0,    0,
      265,  265,  264,  264,  267,    0,  268,  267,  267,  268,
      268,  269,    0,  271,  269,  269,  271,  271,  272,    0,
      273,  272,  272,  273,  273,  275,    0,  276,  275,  275,
      276,  276,  277,    0,  279,  277,  277,  279,  279,  280,
        0,  281,  280,  280,  281,  281,  282,    0,  283,  282,
      282,  283,  283,  285,  285,  287,    0,    0,  287,  287,
      285,  285,  288,    0,  289,  288,  288,  289,  289,  291,
        0,  292,  291,  291,  292,  292,  293,    0,  295,  293,

      293,  295,  295,  296,    0,  297,  296,  296,  297,  297,
      299,    0,  300,  299,  299,  300,  300,  301,    0,  302,
      301,  301,  302,  302,  303,    0,    0,  303,  303,  305,
      305,  306,    0,    0,  306,  306,  305,  305,  308,    0,
      309,  308,  308,  309,  309,  310,    0,  312,  310,  310,
      312,  312,  313,    0,  314,  313,  313,  314,  314,  316,
        0,  317,  316,  316,  317,  317,  318,    0,  319,  318,
      318,  319,  319,  320,    0,    0,  320,  320,  322,  322,
      324,    0,    0,  324,  324,  322,  322,  325,    0,  326,
      325,  325,  326,  326,  328,    0,  329,  328,  328,  329,

      329,  330,    0,  332,  330,  330,  332,  332,  333,    0,
      334,  333,  333,  334,  334,  335,    0,  336,  335,  335,
      336,  336,  338,  338,  339,    0,    0,  339,  339,  338,
      338,  341,    0,  342,  341,  341,  342,  342,  343,    0,
      345,  343,  343,  345,  345,  346,    0,  347,  346,  346,
      347,  347,  348,    0,  349,  348,  348,  349,  349,  351,
      351,  353,    0,    0,  353,  353,  351,  351,  354,    0,
      355,  354,  354,  355,  355,  357,    0,  358,  357,  357,
      358,  358,  359,    0,  360,  359,  359,  360,  360,  361,
        0,    0,  361,  361,  363,  363,  364,    0,    0,  364,

      364,  363,  363,  366,    0,  367,  366,  366,  367,  367,
      368,    0,  369,  368,  368,  369,  369,  370,    0,    0,
      370,  370,  372,  372,  374,    0,    0,  374,  374,  372,
      372,  375,    0,  376,  375,  375,  376,  376,  377,    0,
      378,  377,  377,  378,  378,  381,    0,  382,  381,  381,
      382,  382,  383,    0,  384,  383,  383,  384,  384,  385,
        0,    0,  385,  385,  387,    0,  387,  387,  387,  388,
      388,  389,  389,  390,  390,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "arqlex.l"
#line 2 "arqlex.l"
#include <math.h>
#include <stdio.h>
#include <string.h>
#include "hashmap.h"

#line 807 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 35 "arqlex.l"


#line 997 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 387 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 976 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "arqlex.l"
printf("%s - Inteiro grande demais\n", yytext);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 38 "arqlex.l"
printf("%s - numero_int\n", yytext);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "arqlex.l"
printf("%s - numero_real\n", yytext);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "arqlex.l"
printf("%s - Identificador grande demais\n", yytext);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "arqlex.l"
searchElement(yytext);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "arqlex.l"
printf("%s - .\n", yytext);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 43 "arqlex.l"
printf("%s - ;\n", yytext);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 44 "arqlex.l"
printf("%s - :=\n", yytext);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 45 "arqlex.l"
printf("%s - :\n", yytext);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 46 "arqlex.l"
printf("%s - )\n", yytext);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 47 "arqlex.l"
printf("%s - (\n", yytext);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 48 "arqlex.l"
printf("%s - ,\n", yytext);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 49 "arqlex.l"
printf("%s - >=\n", yytext);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 50 "arqlex.l"
printf("%s - <=\n", yytext);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 51 "arqlex.l"
printf("%s - <>\n", yytext);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 52 "arqlex.l"
printf("%s - <\n", yytext);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 53 "arqlex.l"
printf("%s - >\n", yytext);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 54 "arqlex.l"
printf("%s - =\n", yytext);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 55 "arqlex.l"
printf("%s - +\n", yytext);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 56 "arqlex.l"
printf("%s - -\n", yytext);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 57 "arqlex.l"
printf("%s - *\n", yytext);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 58 "arqlex.l"
printf("%s - /\n", yytext);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "arqlex.l"
printf("%s - Numero inteiro mal formado\n", yytext);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "arqlex.l"
printf("%s - Numero real mal formado\n", yytext);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 61 "arqlex.l"
; 	/* elimina comentarios de uma linha */
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 62 "arqlex.l"
printf("%s - Comentario inacabado\n", yytext);
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 63 "arqlex.l"
; 	/* elimina espaços em branco */
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 64 "arqlex.l"
printf("%s - Caracter Invalido\n", yytext);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "arqlex.l"
ECHO;
	YY_BREAK
#line 1226 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 387 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 387 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 386);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 67 "arqlex.l"



int main(int argc, char *argv[])
{
	initTable();
	++argv, --argc; /* skip over program name */
	if (argc > 0)
		yyin = fopen(argv[0], "r");
	else
		yyin = stdin;
	yylex();
}
int yywrap(){return 1;}
