
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 30
#define YY_END_OF_BUFFER 31
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[388] =
    {   0,
        0,    0,   31,   29,   27,   28,   11,   10,   21,   19,
       12,   20,    6,   22,   29,    2,    9,    7,   16,   18,
       17,    5,   26,   27,   28,    0,    2,    0,    0,    0,
        2,    2,   23,    8,   14,   15,   13,    5,    5,    5,
       26,   25,    3,   24,   24,    0,    0,    2,    0,    2,
        2,   23,    5,    5,   24,   24,    0,    0,    0,    2,
        0,    0,    2,    2,    5,    5,    0,    0,    0,    0,
        2,    0,    0,    2,    2,    5,    5,    0,    0,    0,
        0,    0,    0,    0,    2,    0,    0,    2,    2,    5,
        5,    0,    0,    0,    0,    0,    0,    0,    0,    2,

        0,    0,    2,    2,    5,    5,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    2,    0,    0,
        2,    2,    5,    5,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    2,    0,    0,    2,
        2,    5,    5,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    0,
        0,    2,    2,    5,    5,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    2,    0,    0,    2,    1,    5,    5,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    1,    1,    1,    0,
        1,    1,    5,    5,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
        1,    0,    1,    1,    1,    1,    1,    1,    5,    5,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    1,    1,    0,    1,    1,    1,
        1,    1,    1,    5,    5,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    1,    1,    0,    1,
        1,    1,    1,    1,    5,    5,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    1,    1,    0,    1,

        1,    1,    1,    1,    5,    5,    0,    0,    0,    0,
        0,    0,    0,    1,    1,    0,    1,    1,    1,    1,
        1,    5,    5,    0,    0,    0,    0,    0,    0,    1,
        1,    0,    1,    1,    1,    1,    1,    5,    5,    0,
        0,    0,    1,    1,    0,    1,    1,    1,    1,    1,
        5,    5,    0,    0,    1,    1,    0,    1,    1,    1,
        1,    1,    5,    4,    1,    0,    1,    1,    1,    1,
        1,    4,    4,    0,    1,    1,    1,    1,    1,    4,
        4,    1,    1,    1,    1,    1,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    4,
        5,    6,    7,    8,    9,   10,   11,   12,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,   16,
       17,   18,    1,    1,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
        1,    1,    1,    1,   20,    1,   19,   19,   19,   19,

       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   21,    1,   22,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[23] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    4,    4,    1,    1,    1,    1,    1,    4,    5,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[392] =
    {   0,
        0,    0,  542,  970,  539,  531,  970,  970,  970,  970,
      970,   11,  970,  970,   15,   26,  510,  970,   12,  970,
      503,   34,  491,  504,  496,    0,    0,   29,  482,  473,
       13,   46,  475,  970,  970,  970,  970,    0,   54,    0,
      457,  970,   31,   49,   51,  468,   63,   18,  458,    0,
       68,  454,    0,   76,   71,   73,  444,   85,   90,   38,
       92,  437,    0,   97,    0,  105,   99,  430,  110,  117,
      101,  119,  423,    0,  124,    0,  132,  417,  126,  137,
      144,  416,  146,  151,  102,  153,  411,    0,  158,    0,
      166,  160,  410,  171,  178,  180,  409,  185,  187,  128,

      192,  399,    0,  197,    0,  205,  398,  199,  210,  217,
      391,  219,  224,  226,  384,  231,  233,  129,  238,  377,
        0,  243,    0,  251,  245,  370,  256,  263,  265,  363,
      270,  272,  277,  357,  279,  284,  162,  286,  356,    0,
      291,    0,  299,  351,  293,  304,  311,  350,  313,  318,
      320,  349,  325,  327,  332,  336,  334,  339,  163,  341,
      329,    0,  346,    0,  354,  348,  322,  359,  366,  368,
      315,  373,  375,  380,  308,  382,  387,  389,  302,  394,
      396,  201,  401,  301,    0,  406,    0,  414,  296,  408,
      419,  426,  295,  428,  433,  435,  294,  440,  442,  447,

      281,  449,  454,  456,  274,  461,  463,  202,  468,  267,
        0,  190,    0,  470,  475,  260,  482,  484,  489,  254,
      491,  496,  498,  248,  503,  505,  510,  246,  512,  517,
      519,  236,  524,  526,  247,  531,    0,    0,    0,  533,
      235,  538,  545,  547,  228,  552,  554,  559,  221,  561,
      566,  568,  214,  573,  575,  580,  200,  582,  587,  589,
      594,  596,    0,    0,  598,  603,  182,  610,  612,  617,
      175,  619,  624,  626,  161,  631,  633,  638,  148,  640,
      645,  647,  652,  654,    0,  656,  141,  661,  668,  670,
      127,  675,  677,  682,  114,  684,  689,  691,  100,  696,

      698,  703,  705,  710,    0,  712,  717,   87,  724,  726,
      731,   80,  733,  738,  740,   78,  745,  747,  752,  754,
      759,    0,  761,   69,  766,  773,  775,   66,  780,  782,
      787,   58,  789,  794,  796,  801,  803,    0,  805,  810,
       56,  817,  819,  824,   47,  826,  831,  833,  838,  840,
        0,  842,   39,  847,  854,  856,   36,  861,  863,  868,
      870,  875,    0,  877,  882,   27,  889,  891,  896,  898,
      903,    0,  905,   20,  910,  917,  919,  924,  926,    0,
        0,  931,  933,  938,  940,  945,  970,  958,  961,  963,
      964

    } ;

static yyconst flex_int16_t yy_def[392] =
    {   0,
      387,    1,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  388,  387,  387,   15,   16,  387,  389,  387,
       16,  387,  390,  387,  387,  387,  387,   22,  387,  391,
      388,  387,  387,  387,  387,  389,  387,   32,  387,   48,
      387,  390,   39,  387,  387,  387,  387,  387,  387,   51,
      387,  387,   60,  387,   54,  387,  387,  387,  387,  387,
       64,  387,  387,   71,  387,   66,  387,  387,  387,  387,
      387,  387,  387,  387,   75,  387,  387,   85,  387,   77,
      387,  387,  387,  387,  387,  387,  387,  387,  387,   89,

      387,  387,  100,  387,   91,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  104,  387,  387,
      118,  387,  106,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  122,  387,  387,  137,
      387,  124,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  141,  387,
      387,  159,  387,  143,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  163,  387,  387,  182,  387,  165,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,

      387,  387,  387,  387,  387,  387,  387,  186,  387,  387,
      208,  186,  188,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  212,  387,  235,  212,  214,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  235,  240,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  265,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,

      387,  387,  387,  387,  286,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  306,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  323,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      339,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  352,  387,  387,  387,  387,  387,  387,  387,
      387,  364,  387,  387,  387,  387,  387,  387,  387,  373,
      373,  387,  387,  387,  387,  387,    0,  387,  387,  387,
      387

    } ;

static yyconst flex_int16_t yy_nxt[993] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,    4,
       23,    4,   26,   27,   28,   48,   26,   26,   35,   36,
       60,   29,  382,   29,   30,   28,   29,   31,   32,  377,
       43,   43,   43,   43,   33,   38,   38,   44,  369,   44,
       71,  365,   39,   40,   49,   28,   29,   50,   51,  360,
       55,   55,   56,   56,   33,   53,   53,   55,  356,   56,
      348,   57,   54,   40,   58,   59,   62,   28,  344,   63,
       64,  340,   55,   55,   56,   56,   33,   65,   65,   55,
      335,   56,  331,   57,   66,   40,   58,   59,   68,  327,

       68,   69,   70,   69,   70,   73,   28,   78,   74,   75,
       79,   80,  319,   85,  100,   33,   76,   76,   68,   29,
       29,   69,   70,   77,   40,   82,  315,   82,   83,   84,
       83,   84,   87,   28,   78,   88,   89,   79,   80,  311,
      118,  137,   33,   90,   90,   93,   29,   29,   94,   95,
       91,   40,   93,  307,   82,   94,   95,   83,   84,   97,
      302,   97,   98,   99,   98,   99,  102,   28,  107,  103,
      104,  108,  109,  298,  159,  182,   33,  105,  105,   93,
       29,   29,   94,   95,  106,   40,  111,  294,  111,  112,
      113,  112,  113,   97,  290,  115,   98,   99,  116,  117,

      115,  237,  238,  116,  117,  120,   28,  107,  121,  122,
      108,  109,  282,  208,  235,   33,  123,  123,  126,   29,
       29,  127,  128,  124,   40,  126,  278,  111,  127,  128,
      112,  113,  130,  274,  130,  131,  132,  131,  132,  115,
      270,  134,  116,  117,  135,  136,  134,  266,  260,  135,
      136,  139,   28,  144,  140,  141,  145,  146,  256,  263,
      252,   33,  142,  142,  126,   29,  248,  127,  128,  143,
       40,  148,  244,  148,  149,  150,  149,  150,  130,  236,
      152,  131,  132,  153,  154,  152,  231,  134,  153,  154,
      135,  136,  156,  227,  156,  157,  158,  157,  158,  161,

       28,  144,  162,  163,  145,  146,  223,  219,  215,   33,
      164,  164,  167,  209,  204,  168,  169,  165,   40,  167,
      200,  148,  168,  169,  149,  150,  171,  196,  171,  172,
      173,  172,  173,  152,  192,  175,  153,  154,  176,  177,
      175,  183,  156,  176,  177,  157,  158,  179,  178,  179,
      180,  181,  180,  181,  184,   28,  189,  185,  186,  190,
      191,  174,  170,  166,   33,  187,  187,  167,  160,  155,
      168,  169,  188,   40,  193,  151,  193,  194,  195,  194,
      195,  171,  147,  197,  172,  173,  198,  199,  197,  138,
      175,  198,  199,  176,  177,  201,  133,  201,  202,  203,

      202,  203,  179,  129,  205,  180,  181,  206,  207,  205,
      125,  119,  206,  207,  210,   28,  189,  211,  212,  190,
      191,  114,  110,  101,   33,  213,  213,  216,   96,   92,
      217,  218,  214,   40,  216,   86,  193,  217,  218,  194,
      195,  220,   81,  220,  221,  222,  221,  222,  197,   72,
      224,  198,  199,  225,  226,  224,   67,  201,  225,  226,
      202,  203,  228,   45,  228,  229,  230,  229,  230,  205,
       61,  232,  206,  207,  233,  234,  232,   45,   42,  233,
      234,  239,  239,  241,   45,   47,  242,  243,  240,   40,
      216,   45,  245,  217,  218,  246,  247,  245,   25,  220,

      246,  247,  221,  222,  249,   24,  249,  250,  251,  250,
      251,  224,   42,  253,  225,  226,  254,  255,  253,   37,
      228,  254,  255,  229,  230,  257,   34,  257,  258,  259,
      258,  259,  232,   25,  232,  233,  234,  261,  262,  232,
       24,  387,  261,  262,  264,  264,  241,  387,  387,  242,
      243,  265,   40,  267,  387,  267,  268,  269,  268,  269,
      245,  387,  271,  246,  247,  272,  273,  271,  387,  249,
      272,  273,  250,  251,  275,  387,  275,  276,  277,  276,
      277,  253,  387,  279,  254,  255,  280,  281,  279,  387,
      257,  280,  281,  258,  259,  257,  387,  257,  283,  284,

      283,  284,  232,  387,  232,  261,  262,  261,  262,  285,
      285,  287,  387,  387,  288,  289,  286,   40,  267,  387,
      291,  268,  269,  292,  293,  291,  387,  271,  292,  293,
      272,  273,  295,  387,  295,  296,  297,  296,  297,  275,
      387,  299,  276,  277,  300,  301,  299,  387,  279,  300,
      301,  280,  281,  279,  387,  279,  303,  304,  303,  304,
      257,  387,  257,  283,  284,  283,  284,  305,  305,  287,
      387,  387,  288,  289,  306,   40,  308,  387,  308,  309,
      310,  309,  310,  291,  387,  312,  292,  293,  313,  314,
      312,  387,  295,  313,  314,  296,  297,  316,  387,  316,

      317,  318,  317,  318,  299,  387,  299,  300,  301,  320,
      321,  299,  387,  279,  320,  321,  303,  304,  279,  387,
      387,  303,  304,  322,  322,  324,  387,  387,  325,  326,
      323,   40,  308,  387,  328,  309,  310,  329,  330,  328,
      387,  312,  329,  330,  313,  314,  332,  387,  332,  333,
      334,  333,  334,  316,  387,  316,  317,  318,  336,  337,
      316,  387,  299,  336,  337,  320,  321,  299,  387,  387,
      320,  321,  338,  338,  324,  387,  387,  325,  326,  339,
       40,  341,  387,  341,  342,  343,  342,  343,  328,  387,
      345,  329,  330,  346,  347,  345,  387,  332,  346,  347,

      333,  334,  332,  387,  332,  349,  350,  349,  350,  316,
      387,  316,  336,  337,  336,  337,  351,  351,  353,  387,
      387,  354,  355,  352,   40,  341,  387,  357,  342,  343,
      358,  359,  357,  387,  345,  358,  359,  346,  347,  345,
      387,  345,  361,  362,  361,  362,  332,  387,  332,  349,
      350,  349,  350,  363,  363,  353,  387,  387,  354,  355,
      364,   40,  366,  387,  366,  367,  368,  367,  368,  357,
      387,  357,  358,  359,  370,  371,  357,  387,  345,  370,
      371,  361,  362,  345,  387,  387,  361,  362,  372,  372,
      374,  387,  387,  375,  376,  373,   40,  366,  387,  366,

      367,  368,  378,  379,  366,  387,  357,  378,  379,  370,
      371,  357,  387,  387,  370,  371,  380,  380,  374,  387,
      387,  375,  376,  381,   40,  374,  387,  374,  383,  384,
      383,  384,  366,  387,  366,  378,  379,  378,  379,  374,
      387,  374,  385,  386,  383,  384,  374,  387,  374,  383,
      384,  385,  386,  374,  387,  387,  385,  386,   41,  387,
       41,   41,   41,   46,   46,   52,   52,   40,   40,    3,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387

    } ;

static yyconst flex_int16_t yy_chk[993] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   12,   12,   15,   31,   15,   15,   19,   19,
       48,   31,  374,   15,   16,   16,   48,   16,   16,  366,
       28,   28,   43,   43,   16,   22,   22,   28,  357,   43,
       60,  353,   22,   22,   32,   32,   60,   32,   32,  345,
       44,   44,   45,   45,   32,   39,   39,   44,  341,   45,
      332,   47,   39,   39,   47,   47,   51,   51,  328,   51,
       51,  324,   55,   55,   56,   56,   51,   54,   54,   55,
      316,   56,  312,   58,   54,   54,   58,   58,   59,  308,

       61,   59,   59,   61,   61,   64,   64,   67,   64,   64,
       67,   67,  299,   71,   85,   64,   66,   66,   69,   71,
       85,   69,   69,   66,   66,   70,  295,   72,   70,   70,
       72,   72,   75,   75,   79,   75,   75,   79,   79,  291,
      100,  118,   75,   77,   77,   80,  100,  118,   80,   80,
       77,   77,   81,  287,   83,   81,   81,   83,   83,   84,
      279,   86,   84,   84,   86,   86,   89,   89,   92,   89,
       89,   92,   92,  275,  137,  159,   89,   91,   91,   94,
      137,  159,   94,   94,   91,   91,   95,  271,   96,   95,
       95,   96,   96,   98,  267,   99,   98,   98,   99,   99,

      101,  212,  212,  101,  101,  104,  104,  108,  104,  104,
      108,  108,  257,  182,  208,  104,  106,  106,  109,  182,
      208,  109,  109,  106,  106,  110,  253,  112,  110,  110,
      112,  112,  113,  249,  114,  113,  113,  114,  114,  116,
      245,  117,  116,  116,  117,  117,  119,  241,  232,  119,
      119,  122,  122,  125,  122,  122,  125,  125,  228,  235,
      224,  122,  124,  124,  127,  235,  220,  127,  127,  124,
      124,  128,  216,  129,  128,  128,  129,  129,  131,  210,
      132,  131,  131,  132,  132,  133,  205,  135,  133,  133,
      135,  135,  136,  201,  138,  136,  136,  138,  138,  141,

      141,  145,  141,  141,  145,  145,  197,  193,  189,  141,
      143,  143,  146,  184,  179,  146,  146,  143,  143,  147,
      175,  149,  147,  147,  149,  149,  150,  171,  151,  150,
      150,  151,  151,  153,  167,  154,  153,  153,  154,  154,
      155,  161,  157,  155,  155,  157,  157,  158,  156,  160,
      158,  158,  160,  160,  163,  163,  166,  163,  163,  166,
      166,  152,  148,  144,  163,  165,  165,  168,  139,  134,
      168,  168,  165,  165,  169,  130,  170,  169,  169,  170,
      170,  172,  126,  173,  172,  172,  173,  173,  174,  120,
      176,  174,  174,  176,  176,  177,  115,  178,  177,  177,

      178,  178,  180,  111,  181,  180,  180,  181,  181,  183,
      107,  102,  183,  183,  186,  186,  190,  186,  186,  190,
      190,   97,   93,   87,  186,  188,  188,  191,   82,   78,
      191,  191,  188,  188,  192,   73,  194,  192,  192,  194,
      194,  195,   68,  196,  195,  195,  196,  196,  198,   62,
      199,  198,  198,  199,  199,  200,   57,  202,  200,  200,
      202,  202,  203,   52,  204,  203,  203,  204,  204,  206,
       49,  207,  206,  206,  207,  207,  209,   46,   41,  209,
      209,  214,  214,  215,   33,   30,  215,  215,  214,  214,
      217,   29,  218,  217,  217,  218,  218,  219,   25,  221,

      219,  219,  221,  221,  222,   24,  223,  222,  222,  223,
      223,  225,   23,  226,  225,  225,  226,  226,  227,   21,
      229,  227,  227,  229,  229,  230,   17,  231,  230,  230,
      231,  231,  233,    6,  234,  233,  233,  234,  234,  236,
        5,    3,  236,  236,  240,  240,  242,    0,    0,  242,
      242,  240,  240,  243,    0,  244,  243,  243,  244,  244,
      246,    0,  247,  246,  246,  247,  247,  248,    0,  250,
      248,  248,  250,  250,  251,    0,  252,  251,  251,  252,
      252,  254,    0,  255,  254,  254,  255,  255,  256,    0,
      258,  256,  256,  258,  258,  259,    0,  260,  259,  259,

      260,  260,  261,    0,  262,  261,  261,  262,  262,  265,
      265,  266,    0,    0,  266,  266,  265,  265,  268,    0,
      269,  268,  268,  269,  269,  270,    0,  272,  270,  270,
      272,  272,  273,    0,  274,  273,  273,  274,  274,  276,
        0,  277,  276,  276,  277,  277,  278,    0,  280,  278,
      278,  280,  280,  281,    0,  282,  281,  281,  282,  282,
      283,    0,  284,  283,  283,  284,  284,  286,  286,  288,
        0,    0,  288,  288,  286,  286,  289,    0,  290,  289,
      289,  290,  290,  292,    0,  293,  292,  292,  293,  293,
      294,    0,  296,  294,  294,  296,  296,  297,    0,  298,

      297,  297,  298,  298,  300,    0,  301,  300,  300,  301,
      301,  302,    0,  303,  302,  302,  303,  303,  304,    0,
        0,  304,  304,  306,  306,  307,    0,    0,  307,  307,
      306,  306,  309,    0,  310,  309,  309,  310,  310,  311,
        0,  313,  311,  311,  313,  313,  314,    0,  315,  314,
      314,  315,  315,  317,    0,  318,  317,  317,  318,  318,
      319,    0,  320,  319,  319,  320,  320,  321,    0,    0,
      321,  321,  323,  323,  325,    0,    0,  325,  325,  323,
      323,  326,    0,  327,  326,  326,  327,  327,  329,    0,
      330,  329,  329,  330,  330,  331,    0,  333,  331,  331,

      333,  333,  334,    0,  335,  334,  334,  335,  335,  336,
        0,  337,  336,  336,  337,  337,  339,  339,  340,    0,
        0,  340,  340,  339,  339,  342,    0,  343,  342,  342,
      343,  343,  344,    0,  346,  344,  344,  346,  346,  347,
        0,  348,  347,  347,  348,  348,  349,    0,  350,  349,
      349,  350,  350,  352,  352,  354,    0,    0,  354,  354,
      352,  352,  355,    0,  356,  355,  355,  356,  356,  358,
        0,  359,  358,  358,  359,  359,  360,    0,  361,  360,
      360,  361,  361,  362,    0,    0,  362,  362,  364,  364,
      365,    0,    0,  365,  365,  364,  364,  367,    0,  368,

      367,  367,  368,  368,  369,    0,  370,  369,  369,  370,
      370,  371,    0,    0,  371,  371,  373,  373,  375,    0,
        0,  375,  375,  373,  373,  376,    0,  377,  376,  376,
      377,  377,  378,    0,  379,  378,  378,  379,  379,  382,
        0,  383,  382,  382,  383,  383,  384,    0,  385,  384,
      384,  385,  385,  386,    0,    0,  386,  386,  388,    0,
      388,  388,  388,  389,  389,  390,  390,  391,  391,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "arqlex.l"
#line 2 "arqlex.l"
#include <math.h>
#include <stdio.h>
#include <string.h>
#include "hashmap.h"
#include "y.tab.h"


int yylineno;

#line 815 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 39 "arqlex.l"


#line 1005 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 388 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 970 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "arqlex.l"
return INTEIROGRANDEDEMAIS;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 42 "arqlex.l"
return NUMERO_INT;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "arqlex.l"
return NUMERO_REAL;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "arqlex.l"
return IDGRANDEDEMAIS;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 45 "arqlex.l"
return searchElement(yytext);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 46 "arqlex.l"
return PONTO;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 47 "arqlex.l"
return PONTOEVIRGULA; 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 48 "arqlex.l"
return ATRIBUICAO;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 49 "arqlex.l"
return DOISPONTOS;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 50 "arqlex.l"
return APARENTESES;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 51 "arqlex.l"
return FPARENTESES;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 52 "arqlex.l"
return VIRGULA;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 53 "arqlex.l"
return MAIORIGUAL;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "arqlex.l"
return MENORIGUAL;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "arqlex.l"
return DIFERENTE;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "arqlex.l"
return MENOR;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "arqlex.l"
return MAIOR;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 58 "arqlex.l"
return IGUAL;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 59 "arqlex.l"
return SOMA;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 60 "arqlex.l"
return SUBTRACAO;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 61 "arqlex.l"
return MULTIPLICACAO;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 62 "arqlex.l"
return DIVISAO;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 63 "arqlex.l"
return NUMEROMALFORMADO;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 64 "arqlex.l"
return NUMEROMALFORMADO;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 65 "arqlex.l"
; 	/* elimina comentarios de uma linha */
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 66 "arqlex.l"
printf("%s - Comentario inacabado\n", yytext);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 67 "arqlex.l"
; 	/* elimina espaços em branco */
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 68 "arqlex.l"
yylineno++;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 69 "arqlex.l"
return CARACTERINVALIDO;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "arqlex.l"
ECHO;
	YY_BREAK
#line 1239 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 388 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 388 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 387);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 72 "arqlex.l"



int yywrap(){return 1;}
